
export const celebrities = [
    {
      name: "Brad Pitt",
      imageSrc: "/images/Brad_Pitt-69858.jpg",
      imageAlt: "Brad Pitt",
      videoPoster: "/images/imageforthevid.webp",
      videoSrcMp4: "/images/Watch Brad Pitt Thank His Kids During 2020 Oscars Speech.mp4",
      videoSrcOgg: "/images/Watch Brad Pitt Thank His Kids During 2020 Oscars Speech.ogg",
      videoSrcWebm: "/images/Watch Brad Pitt Thank His Kids During 2020 Oscars Speech.webm",
      videoDescription: "Watch Brad Pitt's speech at the 2020 Oscars",
    },
    {
      name: "Morgan Freeman",
      imageSrc: "/images/morgan freemanS.jpg",
      imageAlt: "Morgan Freeman",
      videoPoster: "/images/poster-morgan-freemanS.jpg",
      videoSrcMp4: "/images/morgan freeman `s best acting ,NO.1 movie (IMDB) and best scene of TSR.mp4",
      videoSrcOgg: "/images/morgan freeman `s best acting ,NO.1 movie (IMDB) and best scene of TSR.ogg",
      videoSrcWebm: "/images/morgan freeman `s best acting ,NO.1 movie (IMDB) and best scene of TSR.webm",
      videoDescription: "Watch Morgan Freeman acting in The Shawshank Redemption",
    },
    {
      name: "Angelina Jolie",
      imageSrc: "/images/angelina jolieS.jpg",
      imageAlt: "Angelina Jolie",
      videoPoster: "/images/posterangelinaS.jpg",
      videoSrcMp4: "/images/Angelina Jolie Will Always Land on Her Feet .mp4",
      videoSrcOgg: "/images/Angelina Jolie Will Always Land on Her Feet .ogg",
      videoSrcWebm: "/images/Angelina Jolie Will Always Land on Her Feet .webm",
      videoDescription: "Watch Angelina Jolie interview with W magazine",
    },
    {
      name: "Jenna Ortega",
      imageSrc: "/images/jenna ortegaS.jpg",
      imageAlt: "Jenna Ortega",
      videoPoster: "/images/jennaposterS.jpg",
      videoSrcMp4: "/images/jennaVid.mp4",
      videoSrcOgg: "/images/jennaVid.ogg",
      videoSrcWebm: "/images/jennaVid.webm",
      videoDescription: "Watch Jenna Ortega with Adidas",
    },
    {
      name: "Theo James",
      imageSrc: "/images/theo jamesS.jpg",
      imageAlt: "Theo James",
      videoPoster: "/images/postertheoS.webp",
      videoSrcMp4: "/images/Range Rover Sport .mp4",
      videoSrcOgg: "/images/Range Rover Sport .ogg",
      videoSrcWebm: "/images/Range Rover Sport .webm",
      videoDescription: "Introducing Theo James for Range Rover Sport",
    },
    {
      name: "Millie Bobby Brown",
      imageSrc: "/images/millieS.jpg",
      imageAlt: "Millie Bobby Brown",
      videoPoster: "/images/postermillieS.jpg",
      videoSrcMp4: "/images/Millie Bobby Brown Ranks her haircuts .mp4",
      videoSrcOgg: "/Millie Bobby Brown Ranks her haircuts .ogg",
      videoSrcWebm: "/Millie Bobby Brown Ranks her haircuts .webm",
      videoDescription: "Millie Bobby Brown and her dog Winnie rank Millie's haircuts",
    },
    {
      name: "Adele",
      imageSrc: "/images/adeleS.webp",
      imageAlt: "Adele",
      videoPoster: "/images/posteradeleS.jpg",
      videoSrcMp4: "/images/Adele Being a Songwriting Genius for 5 minutes.mp4",
      videoSrcOgg: "/Adele Being a Songwriting Genius for 5 minutes.ogg",
      videoSrcWebm: "/Adele Being a Songwriting Genius for 5 minutes.webm",
      videoDescription: "Adele Being a Songwriting Genius for 5 minutes",
    },
    {
      name: "Billie Eilish",
      imageSrc: "/images/billieS.jpg",
      imageAlt: "Billie Eilish",
      videoPoster: "/images/posterbillieS.jpg",
      videoSrcMp4: "/images/Billie Eilish_ Same Interview, The Eighth Year (Coming Soon).mp4",
      videoSrcOgg: "/Billie Eilish_ Same Interview, The Eighth Year (Coming Soon).ogg",
      videoSrcWebm: "/Billie Eilish_ Same Interview, The Eighth Year (Coming Soon).webm",
      videoDescription: "Billie Eilish Same Interview, The Eighth Year",
    },
    {
      name: "Taylor Swift",
      imageSrc: "/images/taylorS.jpg",
      imageAlt: "Taylor Swift",
      videoPoster: "/images/postertaylorS.jpg",
      videoSrcMp4: "/images/Taylor Swift Talks About How The ‘All Too Well (10 Minute Version)’ Came About .mp4",
      videoSrcOgg: "/Taylor Swift Talks About How The ‘All Too Well (10 Minute Version)’ Came About .ogg",
      videoSrcWebm: "/Taylor Swift Talks About How The ‘All Too Well (10 Minute Version)’ Came About .webm",
      videoDescription: "Taylor Swift Talks About How The ‘All Too Well (10 Minute Version)’ Came About",
    },
    {
      name: "The Weeknd",
      imageSrc: "/images/the weekndS.jpg",
      imageAlt: "The Weeknd",
      videoPoster: "/images/postertheS.jpg",
      videoSrcMp4: "/images/The Idol I Press Conference I The Weeknd and the _Dark Side_ of the music Industry I Cannes 2023.mp4",
      videoSrcOgg: "/The Idol I Press Conference I The Weeknd and the _Dark Side_ of the music Industry I Cannes 2023.ogg",
      videoSrcWebm: "/The Idol I Press Conference I The Weeknd and the _Dark Side_ of the music Industry I Cannes 2023.webm",
      videoDescription: "The Weeknd and the _Dark Side_ of the music Industry",
    },
    {
      name: "Lana Del Rey",
      imageSrc: "/images/lanaS.avif",
      imageAlt: "Lana Del Rey",
      videoPoster: "/images/posterlanaS.jpg",
      videoSrcMp4: "/images/Lana Del Rey talks new album 'Lasso', the world going country, and her plans for Reading & Leeds.mp4",
      videoSrcOgg: "/Lana Del Rey talks new album 'Lasso', the world going country, and her plans for Reading & Leeds.ogg",
      videoSrcWebm: "/Lana Del Rey talks new album 'Lasso', the world going country, and her plans for Reading & Leeds.webm",
      videoDescription: "Lana Del Rey talks new album the world going country",
    },
    {
      name: "Rihanna",
      imageSrc: "/images/RihannaS.webp",
      imageAlt: "Rihanna",
      videoPoster: "/images/posterrihannaS.jpg",
      videoSrcMp4: "/images/Rihanna ‘Grateful’ for Accomplishments From the Past Year.mp4",
      videoSrcOgg: "/Rihanna ‘Grateful’ for Accomplishments From the Past Year.ogg",
      videoSrcWebm: "/Rihanna ‘Grateful’ for Accomplishments From the Past Year.webm",
      videoDescription: "Rihanna ‘Grateful’ for Accomplishments From the Past Year",
    },
    {
      name: "Lionel Messi",
      imageSrc: "/images/messiS.jpg",
      imageAlt: "Lionel Messi",
      videoPoster: "/images/postermesiiS.webp",
      videoSrcMp4: "/images/LIONEL MESSI MAGIC STEALS THE SHOW .mp4",
      videoSrcOgg: "/LIONEL MESSI MAGIC STEALS THE SHOW .ogg",
      videoSrcWebm: "/LIONEL MESSI MAGIC STEALS THE SHOW .webm",
      videoDescription: "LIONEL MESSI MAGIC STEALS THE SHOW",
    },
    {
      name: "Michael Jordan",
      imageSrc: "/images/jordanS.webp",
      imageAlt: "Michael Jordan",
      videoPoster: "/images/postermichealS.jpg",
      videoSrcMp4: "/images/Best of Michael Jordan’s Playoff Games .mp4",
      videoSrcOgg: "/Best of Michael Jordan’s Playoff Games .ogg",
      videoSrcWebm: "/Best of Michael Jordan’s Playoff Games .webm",
      videoDescription: "Best of Michael Jordan’s Playoff Games",
    },
    {
      name: "Muhammad Ali",
      imageSrc: "/images/aliS.webp",
      imageAlt: "Muhammad Ali",
      videoPoster: "/images/posteraliS.jpg",
      videoSrcMp4: "/images/The Greatest - Muhammad Ali Inspirational Video.mp4",
      videoSrcOgg: "/The Greatest - Muhammad Ali Inspirational Video.ogg",
      videoSrcWebm: "/The Greatest - Muhammad Ali Inspirational Video.webm",
      videoDescription: "The Greatest - Muhammad Ali Inspirational Video",
    },
    {
      name: "Alexia Putellas",
      imageSrc: "/images/alexiaS.jpg",
      imageAlt: "Alexia Putellas",
      videoPoster: "/images/posteralexiaS.jpg",
      videoSrcMp4: "/images/This is Why Alexia Putellas is GOAT of Women Football!.mp4",
      videoSrcOgg: "/This is Why Alexia Putellas is GOAT of Women Football!.ogg",
      videoSrcWebm: "/This is Why Alexia Putellas is GOAT of Women Football!.webm",
      videoDescription: "This is Why Alexia Putellas is GOAT of Women Football!",
    },
    {
      name: "Lewis Hamilton",
      imageSrc: "/images/lewisS.jpg",
      imageAlt: "Lewis Hamilton",
      videoPoster: "/images/posterlewisS.jpg",
      videoSrcMp4: "/images/Lewis Hamilton Drives the Ferrari SF-24 at Mugello! .mp4",
      videoSrcOgg: "/Lewis Hamilton Drives the Ferrari SF-24 at Mugello! .ogg",
      videoSrcWebm: "/Lewis Hamilton Drives the Ferrari SF-24 at Mugello! .webm",
      videoDescription: "Lewis Hamilton Drives the Ferrari SF-24 at Mugello!",
    },
    {
      name: "Cristiano Ronaldo",
      imageSrc: "/images/ronaldoS.jpg",
      imageAlt: "Cristiano Ronaldo",
      videoPoster: "/images/posterronaldoS.jpg",
      videoSrcMp4: "/images/Two years of CR7 in Saudi Arabia_ The interview 🎙️🐐.mp4",
      videoSrcOgg: "/Two years of CR7 in Saudi Arabia_ The interview 🎙️🐐.ogg",
      videoSrcWebm: "/Two years of CR7 in Saudi Arabia_ The interview 🎙️🐐.webm",
      videoDescription: "Two years of CR7 in Saudi Arabia",
    },
  ];
  