export const movies = {
  "Brad Pitt": [
{
  title: 'Fight Club',
  rate: "1999 &#183; 2h 19m &#183;&#11088;8.8",
  summary: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
  picture: "/images/fightclub.jpeg",
  desc: "Fight Club",
  link: "https://youtu.be/BdJKm16Co6M?si=fCN7xBdGfBLXmmWl"
},
{
  title: "Moneyball",
  rate: "2011 &#183; 2h 13m &#183;&#11088;7.6",
  summary: "Oakland A's general manager Billy Beane's successful attempt to assemble a baseball team on a lean budget by employing computer-generated analysis to acquire new players.",
  picture: "/images/moneyball.jpeg",
  desc: "moneyball",
  link: "https://youtu.be/D1R-LwHbld4?si=W3aJg1w6HZfSnhGb"
},
{
  title: "Ocean's Eleven",
  rate: "2001 &#183; 1h 56m &#183;&#11088;7.7",
  summary: "Danny Ocean, a gangster, rounds up a gang of associates to stage a sophisticated and elaborate casino heist which involves robbing three Las Vegas casinos simultaneously during a popular boxing event.",
  picture: "/images/oceans11.jpeg",
  desc: "oceans11",
  link: "https://youtu.be/imm6OR605UI?si=KzVXhhVSAT-ePhod"
},
{
  title: "Troy",
  rate: "2004 &#183; 2h 43m &#183;&#11088;7.3",
  summary: "An adaptation of Homer's great epic, the film follows the assault on Troy by the united Greek forces.",
  picture: "/images/troy.jpeg",
  desc: "troy",
  link: "https://youtu.be/znTLzRJimeY?si=2cicjIRDr6LQRbLW"
},
{
  title: "Inglourious Basterds",
  rate: "2009 &#183; 2h 33m &#183;&#11088;8.4",
  summary: "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.",
  picture: "/images/Inglourious.jpeg",
  desc: "Inglourious",
  link: "https://youtu.be/KnrRy6kSFF0?si=jhatNkLjXxfxjHYb"
},
{
  title: "Once Upon a Time in Hollywood",
  rate: "2019 &#183; 2h 41m &#183;&#11088;7.6",
  summary: "As Hollywood's Golden Age is winding down during the summer of 1969, television actor Rick Dalton and his stunt double Cliff Booth endeavor to achieve lasting success in Hollywood while meeting several colorful characters along the way.",
  picture: "/images/once apon a time in hw.jpeg",
  desc: "once apon a time in hw",
  link: "https://youtu.be/ELeMaP8EPAA?si=iA8ig1quo9-d8jeM"
}
],
"Theo James": [
{
  title: "Allegiant",
  rate: "2016 · 2h · ⭐5.7",
  summary: "After the earth-shattering revelations of Insurgent, Tris must escape with Four beyond the wall that encircles Chicago to finally discover the shocking truth of the world outside.",
  picture: "/images/Allegiant.jpeg",
  desc: "Allegiant",
  link: "https://youtu.be/tE8LEPSTK6A?si=OBv3nCdupJPUDN_3",
},
{
  title: "Divergent",
  rate: "2014 · 2h 19m · ⭐6.6",
  summary: "In a world divided by factions based on virtues, Tris learns she's Divergent and won't fit in. When she discovers a plot to destroy Divergents, Tris and the mysterious Four must find out what makes Divergents dangerous before it's too late.",
  picture: "/images/diverg.jpeg",
  desc: "Divergent",
  link: "https://youtu.be/Aw7Eln_xuWc?si=OjYn9QkTTRzdNqoi",
},
{
  title: "The Secret Scripture",
  rate: "2016 · 1h 48m · ⭐6.7",
  summary: "A woman keeps a diary of her extended stay at a mental hospital.",
  picture: "/images/secretscripture.jpeg",
  desc: "The Secret Scripture",
  link: "https://youtu.be/0PvJTnnythI?si=696LksUgzBq_9tJ3",
},
{
  title: "War on Everyone",
  rate: "2016 · 1h 38m · ⭐5.8",
  summary: "Two corrupt cops set out to blackmail and frame every criminal unfortunate enough to cross their path. Events, however, are complicated by the arrival of someone who appears to be even more dangerous than they are.",
  picture: "/images/War on Everyone.jpeg",
  desc: "War on Everyone",
  link: "https://youtu.be/XQ2L1heHHnk?si=srB01RxBgVMvdzwP",
},
{
  title: "Archive",
  rate: "2020 · 1h 49m · ⭐6.4",
  summary: "2038: George Almore is working on a true human-equivalent AI. His latest prototype is almost ready. This sensitive phase is also the riskiest. Especially as he has a goal that must be hidden at all costs.",
  picture: "/images/Archive.jpeg",
  desc: "Archive",
  link: "https://youtu.be/m0J0BwIzURI?si=gPQ6xM-ZbcTY5n4B",
},
{
  title: "How It Ends",
  rate: "2018 · 1h 54m · ⭐5.1",
  summary: "In the midst of an apocalypse, a man struggles to reach his pregnant fiancé, who is thousands of miles away.",
  picture: "/images/HowItEnds.jpeg",
  desc: "How It Ends",
  link: "https://youtu.be/WJyyJ7lexnM?si=MZQrp9yjpU4FehyE",
},
],
"Jenna Ortega": [
{
  title: "Yes Day",
  rate: "2021 · 1h 29m · ⭐5.7",
  summary: "A mom and dad who usually say no decide to say yes to their kids' wildest requests with a few ground rules on a whirlwind day of fun and adventure.",
  picture: "/images/Yes Day.jpeg",
  desc: "Yes Day",
  link: "https://youtu.be/Y-3Vr8Ut8d0?si=cr9xxQVnPVN1QXDd",
},
{
  title: "Iron Man 3",
  rate: "2013 · 2h 10m · ⭐5.7",
  summary: "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.",
  picture: "/images/Iron Man 3.jpeg",
  desc: "Iron Man 3",
  link: "https://youtu.be/YLorLVa95Xo?si=diVCUMOB7T4XGbEq",
},
{
  title: "Saving Flora",
  rate: "2018 · 1h 35m · ⭐5.9",
  summary: "Flora is a circus elephant who can no longer perform her tricks. The night before she's scheduled to be euthanized, the circus owner's 14-year-old daughter, Dawn, sneaks Flora from the circus.",
  picture: "/images/Saving Flora.jpeg",
  desc: "Saving Flora",
  link: "https://youtu.be/rmGD5TjGhoQ?si=IK3GfxTaoZ2DsozM",
},
{
  title: "Scream VI",
  rate: "2023 · 2h 2m · ⭐6.4",
  summary: "The survivors of the Ghostface killings leave Woodsboro behind and start a fresh chapter in New York City.",
  picture: "/images/Scream VI.jpeg",
  desc: "Scream VI",
  link: "https://youtu.be/h74AXqw4Opc?si=r9g01mwvGzUCSen6",
},
{
  title: "Wednesday",
  rate: "2022 · 1 season · ⭐8.1",
  summary: "Follows Wednesday Addams' years as a student, when she attempts to master her emerging psychic ability, thwart a killing spree, and solve the mystery that embroiled her parents.",
  picture: "/images/Wednesday.jpeg",
  desc: "Wednesday",
  link: "https://youtu.be/Di310WS8zLk?si=hVSEhR92GZAftC4o",
},
{
  title: "The Fallout",
  rate: "2021 · 1h 32m · ⭐7",
  summary: "High schooler Vada navigates the emotional fallout she experiences in the wake of a school tragedy. Relationships with her family, friends, and view of the world are forever altered.",
  picture: "/images/TheFallout.jpeg",
  desc: "The Fallout",
  link: "https://youtu.be/Gtl-6RCOl84?si=iazN3dZRyezNrXwf",
},
],
"Angelina Jolie": [
{
  title: "Maleficent",
  rate: "2010 · 1h 37m · ⭐6.9",
  summary: "A vengeful fairy is driven to curse an infant princess, only to discover that the child could be the one person who can restore peace to their troubled land.",
  picture: "/images/Maleficent.jpeg",
  desc: "Maleficent",
  link: "https://youtu.be/28U4LxdkNWI?si=-qhVCDi_9uLwbOJQ",
},
{
  title: "Salt",
  rate: "2014 · 1h 44m · ⭐6.5",
  summary: "A CIA agent goes on the run after a defector accuses her of being a Russian spy.",
  picture: "/images/Salt.jpeg",
  desc: "Salt",
  link: "https://youtu.be/QZ40WlshNwU?si=2YiXyajYYuTDiK0N",
},
{
  title: "Mr. & Mrs. Smith",
  rate: "2005 · 2h · ⭐6.5",
  summary: "A husband and wife struggle to keep their marriage alive until they realize they are both secretly working as assassins.",
  picture: "/images/Mr. & Mrs.Smith.jpeg",
  desc: "Mr. & Mrs. Smith",
  link: "https://youtu.be/CZ0B22z22pI?si=ckHXl8VG4tgiquXd",
},
{
  title: "Those Who Wish Me Dead",
  rate: "2021 · 1h 40m · ⭐6",
  summary: "A teenage murder witness finds himself pursued by twin assassins in the Montana wilderness with a survival expert tasked with protecting him—and a forest fire threatening to consume them all.",
  picture: "/images/Those Who Wish Me Dead.jpeg",
  desc: "Those Who Wish Me Dead",
  link: "https://youtu.be/sV6VNNjBkcE?si=x8eBzQG95-fx4QRn",
},
{
  title: "Wanted",
  rate: "2008 · 1h 50m · ⭐6.7",
  summary: "A frustrated office worker discovers that he is the son of a professional assassin, and that he shares his father's superhuman killing abilities.",
  picture: "/images/Wanted.jpeg",
  desc: "Wanted",
  link: "https://youtu.be/b9YEdjEKme0?si=yCAgbzrjf0_CzoJY",
},
{
  title: "The Tourist",
  rate: "2010 · 1h 43m · ⭐6",
  summary: "Revolves around Frank, an American tourist visiting Italy to mend a broken heart. Elise is an extraordinary woman who deliberately crosses his path.",
  picture: "/images/TheTourist.jpeg",
  desc: "The Tourist",
  link: "https://youtu.be/5XtbLezJtMg?si=zYCJTLUUOD_ftiTQ",
},
],
"Morgan Freeman": [
{
  title: "The Bucket List",
  rate: "2007 · 1h 37m · ⭐7.4",
  summary: "Two terminally ill men escape from a cancer ward and head off on a road trip with a wish list of to-dos before they die.",
  picture: "/images/The Bucket List.jpeg",
  desc: "The Bucket List",
  link: "https://youtu.be/vc3mkG21ob4?si=WyfUzPCYpD3VZHRW",
},
{
  title: "Olympus Has Fallen",
  rate: "2013 · 2h · ⭐6.5",
  summary: "Secret Service agent Mike Banning finds himself trapped inside the White House in the wake of a terrorist attack and works with national security to rescue the President from his kidnappers.",
  picture: "/images/Olympus Has Fallen.jpeg",
  desc: "Olympus Has Fallen",
  link: "https://youtu.be/ar-IaAx7s8k?si=n9RbbEObT8N26Y5W",
},
{
  title: "Lucy",
  rate: "2014 · 1h 30m · ⭐6.4",
  summary: "A woman, accidentally caught in a dark deal, turns the tables on her captors and transforms into a merciless warrior evolved beyond human logic.",
  picture: "/images/Lucy.jpeg",
  desc: "Lucy",
  link: "https://youtu.be/bN7ksFEVO9U?si=SCAoYQLp9ZGYE_cB",
},
{
  title: "Now You See Me",
  rate: "2013 · 1h 55m · ⭐7.2",
  summary: "An FBI agent and an Interpol detective track a team of illusionists who pull off bank heists during their performances and reward their audiences with the money.",
  picture: "/images/Now You See Me.jpeg",
  desc: "Now You See Me",
  link: "https://youtu.be/4OtM9j2lcUA?si=gWYMtltYwQL5WzOe",
},
{
  title: "The Dark Knight Rises",
  rate: "2012 · 2h 45m · ⭐8.4",
  summary: "Bane, an imposing terrorist, attacks Gotham City and disrupts its eight-year-long period of peace. This forces Bruce Wayne to come out of hiding and don the cape and cowl of Batman again.",
  picture: "/images/The Dark KnightRises.jpeg",
  desc: "The Dark Knight Rises",
  link: "https://youtu.be/g8evyE9TuYk?si=wO-j-W5iU9HnaYIa",
},
{
  title: "Se7en",
  rate: "1995 · 2h 10m · ⭐8.6",
  summary: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
  picture: "/images/Se7en.jpeg",
  desc: "Se7en",
  link: "https://youtu.be/znmZoVkCjpI?si=Tc3miGffCUCvFypG",
},
],
"Millie Brown": [
{
  title: "Enola Holmes",
  rate: "2020 · 2h 3m · ⭐6.6",
  summary: "When Enola Holmes, Sherlock's sister, discovers her mother is missing, she endeavors to find her, becoming a super-sleuth in her own right as she outwits her famous brother and unravels a dangerous conspiracy.",
  picture: "/images/Enola Holmes.jpeg",
  desc: "Enola Holmes",
  link: "https://youtu.be/1d0Zf9sXlHk?si=O1Eal_niovwml7VN",
},
{
  title: "Stranger Things",
  rate: "2016 - present · 4 seasons · ⭐8.7",
  summary: "In 1980s Indiana, a group of young friends witness supernatural forces and secret government exploits. As they search for answers, the children unravel a series of extraordinary mysteries.",
  picture: "/images/Stranger Things.jpeg",
  desc: "Stranger Things",
  link: "https://youtu.be/b9EkMc79ZSU?si=QYh8yWmyGXaaIEU-",
},
{
  title: "Damsel",
  rate: "2024 · 1h 50m · ⭐6.1",
  summary: "A dutiful damsel agrees to marry a handsome prince, only to find the royal family has recruited her as a sacrifice to repay an ancient debt.",
  picture: "/images/Damsel.jpeg",
  desc: "Damsel",
  link: "https://youtu.be/iM150ZWovZM?si=Xj5j4yfOIf3zFad4",
},
{
  title: "Godzilla vs. Kong",
  rate: "2021 · 1h 53m · ⭐6.3",
  summary: "The epic next chapter in the cinematic Monsterverse pits two of the greatest icons in motion picture history against each other--the fearsome Godzilla and the mighty Kong--with humanity caught in the balance.",
  picture: "/images/Godzilla vs. Kong.jpeg",
  desc: "Godzilla vs. Kong",
  link: "https://youtu.be/odM92ap8_c0?si=GEuc42ZP6_2M9zex",
},
{
  title: "Enola Holmes 2",
  rate: "2022 · 2h 9m · ⭐6.8",
  summary: "Now a detective-for-hire, Enola Holmes takes on her first official case to find a missing girl as the sparks of a dangerous conspiracy ignite a mystery that requires the help of friends—and Sherlock himself—to unravel.",
  picture: "/images/EnolaHolmes2.jpeg",
  desc: "Enola Holmes 2",
  link: "https://youtu.be/KKXNmYoPkx0?si=BGFxL3FABlwf6NIw",
},
{
  title: "Intruders",
  rate: "2014 · 1 season · ⭐6.6",
  summary: "A secret society is devoted to chasing immortality by seeking refuge in the bodies of others.",
  picture: "/images/Intruders.jpeg",
  desc: "Intruders",
  link: "https://youtu.be/xwjZHUV8p2k?si=6pAWV7QYQALNvuRh",
},
],
};